import * as fs from 'fs';
import * as path from 'path';

/**
 * Artifact Cleanup Utility
 * Manages test artifacts (screenshots, logs) with configurable retention policies
 *
 * Note: Traces are managed by Playwright's built-in trace configuration (on-first-retry).
 * This utility handles screenshots and logs generated by the Logger utility.
 *
 * Industry Best Practices:
 * - Keep recent test runs for debugging
 * - Auto-cleanup old artifacts to prevent disk bloat
 * - Retain failed test artifacts longer than passed tests
 * - Clean before test runs (not during/after to preserve debugging data)
 */

export interface CleanupConfig {
  /** Keep artifacts newer than this many hours (default: 1) */
  retentionHours?: number;
  /** Keep last N test runs regardless of age (default: 1) */
  keepLastNRuns?: number;
  /** Keep failed test artifacts for longer (default: 1 hour) */
  failedTestRetentionHours?: number;
  /** Enable/disable cleanup (default: true) */
  enabled?: boolean;
  /** Directories to clean */
  directories?: readonly string[];
}

export class ArtifactCleanup {
  private config: Required<CleanupConfig>;
  private baseDir: string;

  constructor(config: CleanupConfig = {}) {
    this.baseDir = process.cwd();
    this.config = {
      retentionHours: config.retentionHours ?? 1,
      keepLastNRuns: config.keepLastNRuns ?? 1,
      failedTestRetentionHours: config.failedTestRetentionHours ?? 1,
      enabled: config.enabled ?? true,
      directories: config.directories ?? [
        'test-results/logs',
        'test-results/success-screenshots',
        'playwright-report/data',
      ],
    };
  }

  /**
   * Execute cleanup based on retention policy
   * Call this BEFORE test execution starts
   */
  async cleanup(): Promise<CleanupReport> {
    if (!this.config.enabled) {
      console.log('🔇 Artifact cleanup disabled');
      return { deleted: 0, kept: 0, errors: [], skipped: true };
    }

    console.log('🧹 Starting artifact cleanup...');
    const report: CleanupReport = { deleted: 0, kept: 0, errors: [], skipped: false };
    const now = Date.now();

    for (const dir of this.config.directories) {
      const fullPath = path.join(this.baseDir, dir);

      if (!fs.existsSync(fullPath)) {
        console.log(`  ⏭️  Skipping ${dir} (doesn't exist)`);
        continue;
      }

      try {
        const files = this.getFilesRecursively(fullPath);
        const sortedFiles = files.sort((a, b) => {
          const statA = fs.statSync(a);
          const statB = fs.statSync(b);
          return statB.mtime.getTime() - statA.mtime.getTime(); // Newest first
        });

        const isFailureDir = dir.includes('failure');
        const retentionMs =
          (isFailureDir ? this.config.failedTestRetentionHours : this.config.retentionHours) *
          60 *
          60 *
          1000;

        for (let i = 0; i < sortedFiles.length; i++) {
          const file = sortedFiles[i];
          const stats = fs.statSync(file);
          const age = now - stats.mtime.getTime();
          const isProtected = i < this.config.keepLastNRuns; // Keep last N runs

          if (isProtected) {
            // Protected: part of last N runs
            report.kept++;
            continue;
          }

          if (age > retentionMs) {
            // Delete: older than retention period
            try {
              fs.unlinkSync(file);
              report.deleted++;
            } catch (err) {
              report.errors.push(`Failed to delete ${file}: ${err}`);
            }
          } else {
            // Keep: within retention period
            report.kept++;
          }
        }

        // Clean empty directories
        this.cleanEmptyDirs(fullPath);
      } catch (err) {
        report.errors.push(`Error processing ${dir}: ${err}`);
      }
    }

    this.logReport(report);
    return report;
  }

  /**
   * Get all files recursively from a directory
   */
  private getFilesRecursively(dir: string): string[] {
    const files: string[] = [];

    if (!fs.existsSync(dir)) {
      return files;
    }

    const entries = fs.readdirSync(dir, { withFileTypes: true });

    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        files.push(...this.getFilesRecursively(fullPath));
      } else {
        files.push(fullPath);
      }
    }

    return files;
  }

  /**
   * Remove empty directories recursively
   */
  private cleanEmptyDirs(dir: string): void {
    if (!fs.existsSync(dir)) {
      return;
    }

    const entries = fs.readdirSync(dir);

    if (entries.length === 0) {
      // Don't delete root directories, only subdirectories
      const isRootDir = this.config.directories.some((d) => path.join(this.baseDir, d) === dir);
      if (!isRootDir) {
        fs.rmdirSync(dir);
      }
      return;
    }

    // Recursively check subdirectories
    for (const entry of entries) {
      const fullPath = path.join(dir, entry);
      if (fs.statSync(fullPath).isDirectory()) {
        this.cleanEmptyDirs(fullPath);
      }
    }

    // Check again if directory is now empty
    const remainingEntries = fs.readdirSync(dir);
    const isRootDir = this.config.directories.some((d) => path.join(this.baseDir, d) === dir);
    if (remainingEntries.length === 0 && !isRootDir) {
      fs.rmdirSync(dir);
    }
  }

  /**
   * Log cleanup report
   */
  private logReport(report: CleanupReport): void {
    if (report.skipped) {
      return;
    }

    console.log('\n📊 Cleanup Summary:');
    console.log(`  ✅ Kept:    ${report.kept} files (recent or protected)`);
    console.log(`  🗑️  Deleted: ${report.deleted} files (expired)`);

    if (report.errors.length > 0) {
      console.log(`  ⚠️  Errors:  ${report.errors.length}`);
      report.errors.forEach((err) => console.log(`     - ${err}`));
    }

    console.log('');
  }

  /**
   * Get current retention policy info
   */
  getRetentionInfo(): string {
    return [
      `📋 Artifact Retention Policy:`,
      `  • Passed tests: Keep for ${this.config.retentionHours}h`,
      `  • Failed tests: Keep for ${this.config.failedTestRetentionHours}h`,
      `  • Always keep: Last ${this.config.keepLastNRuns} runs`,
      `  • Status: ${this.config.enabled ? 'Enabled ✅' : 'Disabled ❌'}`,
    ].join('\n');
  }
}

export interface CleanupReport {
  deleted: number;
  kept: number;
  errors: string[];
  skipped: boolean;
}

/**
 * Cleanup presets for different environments
 */
export const CleanupPresets = {
  /** Local development: Keep logs for 1 hour as per requirement */
  LOCAL: {
    retentionHours: 1,
    keepLastNRuns: 1,
    failedTestRetentionHours: 1, // Same as success, 1 hour
    enabled: true,
    directories: [
      'test-results/logs',
      'test-results/success-screenshots',
      'playwright-report/data',
    ],
  },

  /** CI/CD: Keep for 1 hour */
  CI: {
    retentionHours: 1,
    keepLastNRuns: 1,
    failedTestRetentionHours: 1,
    enabled: true,
    directories: [
      'test-results/logs',
      'test-results/success-screenshots',
      'playwright-report/data',
    ],
  },

  /** Staging: Keep for 1 hour */
  STAGING: {
    retentionHours: 1,
    keepLastNRuns: 1,
    failedTestRetentionHours: 1,
    enabled: true,
    directories: [
      'test-results/logs',
      'test-results/success-screenshots',
      'playwright-report/data',
    ],
  },

  /** Disabled: No cleanup (manual management) */
  DISABLED: {
    enabled: false,
  },
} as const;
